### PR TITLE
Intersphinx mapping to Python 3

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by llllllllll** [comment]
Hey, thanks for opening a pr! Are there any intersphinx mappings which are getting sent to Python 2 currently? I spot checked a couple with a local build and on readthedocs but everything went to Python 3. There is a Python 2 link for `generator functions` in `code-objects`; however, that is an explicit link which is incorrect. If this fixes some mappings or is the new preferred way to intersphinx to Python then I am happy to merge this.

**Comment by ssanderson** [comment]
It looks like `docs.python.org` now redirects to the python 3 docs.  Is that a recent change maybe?

```
In [26]: resp = requests.get('https://docs.python.org')

In [27]: resp.history[0]
Out[27]: <Response [302]>

In [28]: resp.history[0].headers['Location']
Out[28]: 'https://docs.python.org/3/'
```

**Comment by ssanderson** [comment]
It looks to me like this is a functional no-op, but it's saving the python docs from serving an extra web request, so :+1: from me.

**Comment by Carreau** [comment]
Saving the internet one byte at a time.

**Pull request merged**
